// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testcase.proto

package tests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeaderList struct {
	Headers              []string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderList) Reset()         { *m = HeaderList{} }
func (m *HeaderList) String() string { return proto.CompactTextString(m) }
func (*HeaderList) ProtoMessage()    {}
func (*HeaderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_testcase_526948c515ae0700, []int{0}
}
func (m *HeaderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderList.Unmarshal(m, b)
}
func (m *HeaderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderList.Marshal(b, m, deterministic)
}
func (dst *HeaderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderList.Merge(dst, src)
}
func (m *HeaderList) XXX_Size() int {
	return xxx_messageInfo_HeaderList.Size(m)
}
func (m *HeaderList) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderList.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderList proto.InternalMessageInfo

func (m *HeaderList) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type SignedV4Test struct {
	FileName             string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Bucket               string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object               string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Method               string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Expiration           int64                  `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Timestamp            string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExpectedUrl          string                 `protobuf:"bytes,8,opt,name=expectedUrl,proto3" json:"expectedUrl,omitempty"`
	Headers              map[string]*HeaderList `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignedV4Test) Reset()         { *m = SignedV4Test{} }
func (m *SignedV4Test) String() string { return proto.CompactTextString(m) }
func (*SignedV4Test) ProtoMessage()    {}
func (*SignedV4Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_testcase_526948c515ae0700, []int{1}
}
func (m *SignedV4Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedV4Test.Unmarshal(m, b)
}
func (m *SignedV4Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedV4Test.Marshal(b, m, deterministic)
}
func (dst *SignedV4Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedV4Test.Merge(dst, src)
}
func (m *SignedV4Test) XXX_Size() int {
	return xxx_messageInfo_SignedV4Test.Size(m)
}
func (m *SignedV4Test) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedV4Test.DiscardUnknown(m)
}

var xxx_messageInfo_SignedV4Test proto.InternalMessageInfo

func (m *SignedV4Test) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SignedV4Test) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SignedV4Test) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *SignedV4Test) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *SignedV4Test) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SignedV4Test) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *SignedV4Test) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *SignedV4Test) GetExpectedUrl() string {
	if m != nil {
		return m.ExpectedUrl
	}
	return ""
}

func (m *SignedV4Test) GetHeaders() map[string]*HeaderList {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*HeaderList)(nil), "tests.HeaderList")
	proto.RegisterType((*SignedV4Test)(nil), "tests.SignedV4Test")
	proto.RegisterMapType((map[string]*HeaderList)(nil), "tests.SignedV4Test.HeadersEntry")
}

func init() { proto.RegisterFile("testcase.proto", fileDescriptor_testcase_526948c515ae0700) }

var fileDescriptor_testcase_526948c515ae0700 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbb, 0x4f, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0x86, 0x3e, 0x72, 0xa9, 0x10, 0x78, 0x40, 0x56, 0x85, 0x90, 0xd5, 0x01, 0x32,
	0x65, 0x28, 0x0c, 0xa8, 0x3b, 0x12, 0x03, 0x30, 0x84, 0xc7, 0xee, 0x24, 0x07, 0x35, 0xcd, 0x4b,
	0xf6, 0x15, 0xb5, 0x7f, 0x3d, 0x28, 0x76, 0x68, 0xb2, 0xf9, 0xfb, 0x7d, 0xb2, 0x7d, 0xfa, 0x1d,
	0x9c, 0x12, 0x1a, 0xca, 0xa4, 0xc1, 0xb8, 0xd1, 0x35, 0xd5, 0x6c, 0xdc, 0x66, 0xb3, 0xbc, 0x06,
	0x78, 0x44, 0x99, 0xa3, 0x7e, 0x52, 0x86, 0x18, 0x87, 0xe9, 0xc6, 0x26, 0xc3, 0x3d, 0xe1, 0x47,
	0x41, 0xf2, 0x1f, 0x97, 0xbf, 0x23, 0x98, 0xbf, 0xaa, 0xaf, 0x0a, 0xf3, 0x8f, 0xbb, 0x37, 0x34,
	0xc4, 0x16, 0x30, 0xfb, 0x54, 0x05, 0xbe, 0xc8, 0x12, 0xb9, 0x27, 0xbc, 0x28, 0x48, 0x8e, 0x99,
	0x09, 0x08, 0x73, 0x34, 0x99, 0x56, 0x0d, 0xa9, 0xba, 0xe2, 0x23, 0x5b, 0x0f, 0x11, 0xbb, 0x80,
	0x49, 0xba, 0xcb, 0xb6, 0x48, 0xdc, 0xb7, 0x65, 0x97, 0x5a, 0x5e, 0xa7, 0xdf, 0x98, 0x11, 0x3f,
	0x71, 0xdc, 0xa5, 0x96, 0x97, 0x48, 0x9b, 0x3a, 0xe7, 0x63, 0xc7, 0x5d, 0x62, 0x57, 0x00, 0xb8,
	0x6f, 0x94, 0x96, 0xf6, 0xa3, 0x89, 0xf0, 0x22, 0x3f, 0x19, 0x10, 0x76, 0x09, 0x01, 0xa9, 0x12,
	0x0d, 0xc9, 0xb2, 0xe1, 0x53, 0x7b, 0xb5, 0x07, 0xed, 0x9c, 0xb8, 0x6f, 0x30, 0x23, 0xcc, 0xdf,
	0x75, 0xc1, 0x67, 0x6e, 0xce, 0x01, 0x62, 0xeb, 0x5e, 0x48, 0x20, 0xfc, 0x28, 0x5c, 0x89, 0xd8,
	0x7a, 0x8b, 0x87, 0x2e, 0x62, 0x67, 0xd0, 0x3c, 0x54, 0xa4, 0x0f, 0x47, 0x65, 0x8b, 0x67, 0x98,
	0x0f, 0x0b, 0x76, 0x06, 0xfe, 0x16, 0x0f, 0x9d, 0xac, 0xf6, 0xc8, 0x6e, 0x60, 0xfc, 0x23, 0x8b,
	0x1d, 0x5a, 0x43, 0xe1, 0xea, 0xbc, 0x7b, 0xbb, 0x5f, 0x48, 0xe2, 0xfa, 0xf5, 0xe8, 0xde, 0x4b,
	0x27, 0x76, 0x6f, 0xb7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xd7, 0xd8, 0x32, 0xc9, 0x01,
	0x00, 0x00,
}
