// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testcase.proto

package tests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueList struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueList) Reset()         { *m = ValueList{} }
func (m *ValueList) String() string { return proto.CompactTextString(m) }
func (*ValueList) ProtoMessage()    {}
func (*ValueList) Descriptor() ([]byte, []int) {
	return fileDescriptor_testcase_636586d93b7be6d2, []int{0}
}
func (m *ValueList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueList.Unmarshal(m, b)
}
func (m *ValueList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueList.Marshal(b, m, deterministic)
}
func (dst *ValueList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueList.Merge(dst, src)
}
func (m *ValueList) XXX_Size() int {
	return xxx_messageInfo_ValueList.Size(m)
}
func (m *ValueList) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueList.DiscardUnknown(m)
}

var xxx_messageInfo_ValueList proto.InternalMessageInfo

func (m *ValueList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type SignedV4Test struct {
	FileName             string                `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Description          string                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Bucket               string                `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object               string                `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Method               string                `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Expiration           int64                 `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Timestamp            string                `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExpectedUrl          string                `protobuf:"bytes,8,opt,name=expectedUrl,proto3" json:"expectedUrl,omitempty"`
	Headers              map[string]*ValueList `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SignedV4Test) Reset()         { *m = SignedV4Test{} }
func (m *SignedV4Test) String() string { return proto.CompactTextString(m) }
func (*SignedV4Test) ProtoMessage()    {}
func (*SignedV4Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_testcase_636586d93b7be6d2, []int{1}
}
func (m *SignedV4Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedV4Test.Unmarshal(m, b)
}
func (m *SignedV4Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedV4Test.Marshal(b, m, deterministic)
}
func (dst *SignedV4Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedV4Test.Merge(dst, src)
}
func (m *SignedV4Test) XXX_Size() int {
	return xxx_messageInfo_SignedV4Test.Size(m)
}
func (m *SignedV4Test) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedV4Test.DiscardUnknown(m)
}

var xxx_messageInfo_SignedV4Test proto.InternalMessageInfo

func (m *SignedV4Test) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SignedV4Test) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SignedV4Test) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *SignedV4Test) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *SignedV4Test) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SignedV4Test) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *SignedV4Test) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *SignedV4Test) GetExpectedUrl() string {
	if m != nil {
		return m.ExpectedUrl
	}
	return ""
}

func (m *SignedV4Test) GetHeaders() map[string]*ValueList {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Testcases struct {
	SignedV4Tests        []*SignedV4Test `protobuf:"bytes,1,rep,name=signedV4Tests,proto3" json:"signedV4Tests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Testcases) Reset()         { *m = Testcases{} }
func (m *Testcases) String() string { return proto.CompactTextString(m) }
func (*Testcases) ProtoMessage()    {}
func (*Testcases) Descriptor() ([]byte, []int) {
	return fileDescriptor_testcase_636586d93b7be6d2, []int{2}
}
func (m *Testcases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Testcases.Unmarshal(m, b)
}
func (m *Testcases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Testcases.Marshal(b, m, deterministic)
}
func (dst *Testcases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Testcases.Merge(dst, src)
}
func (m *Testcases) XXX_Size() int {
	return xxx_messageInfo_Testcases.Size(m)
}
func (m *Testcases) XXX_DiscardUnknown() {
	xxx_messageInfo_Testcases.DiscardUnknown(m)
}

var xxx_messageInfo_Testcases proto.InternalMessageInfo

func (m *Testcases) GetSignedV4Tests() []*SignedV4Test {
	if m != nil {
		return m.SignedV4Tests
	}
	return nil
}

func init() {
	proto.RegisterType((*ValueList)(nil), "tests.ValueList")
	proto.RegisterType((*SignedV4Test)(nil), "tests.SignedV4Test")
	proto.RegisterMapType((map[string]*ValueList)(nil), "tests.SignedV4Test.HeadersEntry")
	proto.RegisterType((*Testcases)(nil), "tests.Testcases")
}

func init() { proto.RegisterFile("testcase.proto", fileDescriptor_testcase_636586d93b7be6d2) }

var fileDescriptor_testcase_636586d93b7be6d2 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4b, 0xf3, 0x40,
	0x18, 0xc4, 0x49, 0xf3, 0xf6, 0x23, 0x4f, 0xfa, 0x4a, 0x59, 0x41, 0x96, 0x22, 0x12, 0x2a, 0x48,
	0x4e, 0x39, 0x54, 0x0f, 0xda, 0xbb, 0xe2, 0xa1, 0x78, 0x88, 0xb5, 0xf7, 0x34, 0x79, 0xb4, 0x6b,
	0x9b, 0x0f, 0x76, 0x9f, 0x4a, 0xfb, 0xcf, 0x8b, 0xec, 0x6e, 0xac, 0x2b, 0x78, 0xcb, 0xfc, 0x66,
	0x37, 0x3b, 0xcc, 0xc0, 0x09, 0xa1, 0xa2, 0x3c, 0x53, 0x98, 0x34, 0xb2, 0xa6, 0x9a, 0x75, 0xb5,
	0x56, 0x93, 0x4b, 0x08, 0x96, 0xd9, 0x76, 0x87, 0x73, 0xa1, 0x88, 0x9d, 0x41, 0xef, 0x43, 0x0b,
	0xc5, 0xbd, 0xc8, 0x8f, 0x83, 0xb4, 0x55, 0x93, 0xcf, 0x0e, 0x0c, 0x9f, 0xc5, 0x5b, 0x85, 0xc5,
	0xf2, 0x66, 0x81, 0x8a, 0xd8, 0x18, 0x06, 0xaf, 0x62, 0x8b, 0x4f, 0x59, 0x89, 0xdc, 0x8b, 0xbc,
	0x38, 0x48, 0x8f, 0x9a, 0x45, 0x10, 0x16, 0xa8, 0x72, 0x29, 0x1a, 0x12, 0x75, 0xc5, 0x3b, 0xc6,
	0x76, 0x91, 0x7e, 0x66, 0xb5, 0xcb, 0x37, 0x48, 0xdc, 0x37, 0x66, 0xab, 0x34, 0xaf, 0x57, 0xef,
	0x98, 0x13, 0xff, 0x67, 0xb9, 0x55, 0x9a, 0x97, 0x48, 0xeb, 0xba, 0xe0, 0x5d, 0xcb, 0xad, 0x62,
	0x17, 0x00, 0xb8, 0x6f, 0x84, 0xcc, 0xcc, 0x43, 0xbd, 0xc8, 0x8b, 0xfd, 0xd4, 0x21, 0xec, 0x1c,
	0x02, 0x12, 0x25, 0x2a, 0xca, 0xca, 0x86, 0xf7, 0xcd, 0xd5, 0x1f, 0xa0, 0x73, 0xe2, 0xbe, 0xc1,
	0x9c, 0xb0, 0x78, 0x91, 0x5b, 0x3e, 0xb0, 0x39, 0x1d, 0xc4, 0x66, 0xd0, 0x5f, 0x63, 0x56, 0xa0,
	0x54, 0x3c, 0x88, 0xfc, 0x38, 0x9c, 0x46, 0x89, 0x29, 0x2d, 0x71, 0xbb, 0x48, 0x1e, 0xed, 0x91,
	0xfb, 0x8a, 0xe4, 0x21, 0xfd, 0xbe, 0x30, 0x9e, 0xc3, 0xd0, 0x35, 0xd8, 0x08, 0xfc, 0x0d, 0x1e,
	0xda, 0xb2, 0xf4, 0x27, 0xbb, 0x82, 0xae, 0xa9, 0xd7, 0x34, 0x14, 0x4e, 0x47, 0xed, 0xbf, 0x8f,
	0x6b, 0xa4, 0xd6, 0x9e, 0x75, 0x6e, 0xbd, 0xc9, 0x03, 0x04, 0x8b, 0x76, 0x3e, 0xc5, 0xee, 0xe0,
	0xbf, 0x72, 0x02, 0xd8, 0xb1, 0xc2, 0xe9, 0xe9, 0x1f, 0xe1, 0xd2, 0xdf, 0x27, 0x57, 0x3d, 0xb3,
	0xfd, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x24, 0xb7, 0x2c, 0x0d, 0x02, 0x00, 0x00,
}
